Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    raise
RuntimeError: No active exception to reraise