Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
    archivo = open("archivo.txt", "x")
FileExistsError: [Errno 17] File exists: 'archivo.txt'